const FETCH_CITIES = "citiesSearch/SET_CITIES";
const FETCH_CITIES_SUCCEEDED = "citiesSearch/FETCH_CITIES_SUCCEEDED";
const FETCH_CITIES_FAILED = "citiesSearch/FETCH_CITIES_FAILED";
const CLEAN_CITIES = "citiesSearch/CLEAN_CITIES";

const SET_DATA_WEATHER = "weatherData/SET_DATA_WEATHER";
const SET_DATA_WEATHER_SUCCEEDED = "weatherData/SET_DATA_WEATHER_SUCCEEDED";
const SET_DATA_WEATHER_FAILED = "weatherData/SET_DATA_WEATHER_FAILED";
const CLEAN_DATA = "weatherData/CLEAN_DATA";

const SET_FAVORITE = "favorite/SET_FAVORITE";
const CLEAN_FAVORITE = "favorite/CLEAN_FAVORITE";

export default {
  FETCH_CITIES,
  FETCH_CITIES_FAILED,
  FETCH_CITIES_SUCCEEDED,
  CLEAN_CITIES,
  SET_DATA_WEATHER,
  SET_DATA_WEATHER_SUCCEEDED,
  SET_DATA_WEATHER_FAILED,
  CLEAN_DATA,
  SET_FAVORITE,
  CLEAN_FAVORITE
}
